---
- name: Run Python server check script
  hosts: all   # run against whatever group is selected with -l

  tasks:
    - name: Copy check_status.py to node
      copy:
        src:  check_status.py
        dest: /tmp/check_status.py
        mode: '0755'

    - name: Execute check_status.py
      command: python3 /tmp/check_status.py
      register: result

    - name: Show script output
      debug:
        msg: "{{ result.stdout }}"
