---
- name: Run Python server check script
  hosts: all   # run against whatever group is selected with -l

  tasks:
    - name: Copy check_status.py to node
      copy:
        src:  check_status.py
        dest: /tmp/check_status.py
        mode: '0755'

    - name: Execute check_status.py
      command: python3 /tmp/check_status.py
      register: result

    - name: Show script output
      debug:
        msg: "{{ result.stdout }}"

    - name: Copy system_api.py to node
      copy:
        src: system_api.py
        dest: /tmp/system_api.py
        mode: '0755'

    - name: Ensure Flask dependencies installed
      pip:
        name:
          - flask
          - psutil
        executable: pip3
    
    - name: Copy template file to node
      copy:
        src: templates
        dest: /tmp/
        mode: '0755'

    - name: Run Flask API in background
      shell: "nohup python3 /tmp/system_api.py > /tmp/system_api.log 2>&1 &"
      async: 0
      poll: 0