services:
  control:
    build: ./control
    container_name: ansible-control
    volumes:
      - ${HOST_WORKSPACE}/playbook:/ansible/playbook
      - ${HOST_WORKSPACE}/inventory.ini:/ansible/inventory.ini:ro
      - ${HOST_WORKSPACE}/ansible.cfg:/ansible/ansible.cfg:ro
      #- .:/ansible:ro
      - ssh-volume:/control/ssh  # 👈 Shared volume
    environment:
      WORKSPACE: ${HOST_WORKSPACE}   # ✅ This is the correct YAML syntax
    networks:
      - ansible-net
    tty: true
    depends_on:
      node1:
        condition: service_healthy
      node2:
        condition: service_healthy
      node3:
        condition: service_healthy

  node1:
    build: ./node
    container_name: node1
    ports:
      - "5001:5001"   # expose Flask API for Dev
    environment:
      - APP_ENV="DEV"  
      - PYTHONUNBUFFERED=1
    volumes:
      #- ./control/ssh/authorized_keys:/root/.ssh/authorized_keys:ro
      - ssh-volume:/root/.ssh:ro
    networks:
      - ansible-net
    healthcheck:
      test: ["CMD", "pgrep", "sshd"]
      interval: 5s
      retries: 10

  node2:
    build: ./node
    container_name: node2
    ports:
      - "5002:5001"   # expose Flask API for uat
    environment:
      - APP_ENV="UAT"  
    volumes:
      #- ./control/ssh/authorized_keys:/root/.ssh/authorized_keys:ro
      - ssh-volume:/root/.ssh:ro
    networks:
      - ansible-net
    healthcheck:
      test: ["CMD", "pgrep", "sshd"]
      interval: 5s
      retries: 10

  node3:
    build: ./node
    container_name: node3
    ports:
      - "5003:5001"   # expose Flask API for prod
    environment:
      - APP_ENV="PROD"  
    volumes:
      #- ./control/ssh/authorized_keys:/root/.ssh/authorized_keys:ro
      - ssh-volume:/root/.ssh:ro
    networks:
      - ansible-net
    healthcheck:
      test: ["CMD", "pgrep", "sshd"]
      interval: 5s
      retries: 10

volumes:
  ssh-volume:

networks:
  ansible-net: