services:
  control:
    build: ./control
    container_name: ansible-control
    volumes:
      - ./playbook:/ansible/playbook
      - ./inventory.ini:/ansible/inventory.ini:ro
      - ./ansible.cfg:/ansible/ansible.cfg:ro   # 👈 mount ansible.cfg
      - ssh-volume:/control/ssh  # 👈 Shared volume
    networks:
      - ansible-net
    tty: true
    depends_on:
      node1:
        condition: service_healthy
      node2:
        condition: service_healthy
      node3:
        condition: service_healthy

  node1:
    build: ./node
    container_name: node1
    volumes:
      #- ./control/ssh/authorized_keys:/root/.ssh/authorized_keys:ro
      - ssh-volume:/root/.ssh:ro
    networks:
      - ansible-net
    healthcheck:
      test: ["CMD", "pgrep", "sshd"]
      interval: 5s
      retries: 10

  node2:
    build: ./node
    container_name: node2
    volumes:
      #- ./control/ssh/authorized_keys:/root/.ssh/authorized_keys:ro
      - ssh-volume:/root/.ssh:ro
    networks:
      - ansible-net
    healthcheck:
      test: ["CMD", "pgrep", "sshd"]
      interval: 5s
      retries: 10

  node3:
    build: ./node
    container_name: node3
    volumes:
      #- ./control/ssh/authorized_keys:/root/.ssh/authorized_keys:ro
      - ssh-volume:/root/.ssh:ro
    networks:
      - ansible-net
    healthcheck:
      test: ["CMD", "pgrep", "sshd"]
      interval: 5s
      retries: 10

volumes:
  ssh-volume:

networks:
  ansible-net: